name: DatadogCI
on:
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      datadog-agent:
        image: datadog/agent:latest
        ports:
          - 8126:8126
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_INSIDE_CI: "true"
          DD_HOSTNAME: "none"

    steps:
      - uses: actions/checkout@v2

      - name: my-python-app
        env:
          DD_AGENT_HOST: localhost
          DD_ENV: ci
          DD_SERVICE: my-python-app
          DD_TAGS: "team:integration-tools-and-libraries"
          DD_TRACE_ANALYTICS_ENABLED: "true"
          RECORD: "none"
          DD_TRACE_AGENT_URL: "http://localhost:8126"
          PYTEST_ADDOPTS: "--ddtrace"
        run: |
          pip install -U ddtrace
          pip install pytest
          pytest --ddtrace
